### ISSUE TITLE
Better matching on Accept headers

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/pyramid_urireferencer#18]
https://github.com/OnroerendErfgoed/pyramid_urireferencer/blob/master/pyramid_urireferencer/protected_resources.py#L37

Probably better to write something like:
```
if 'application/json' in parent_object.request.accept:
```

**Comment by Wim-De-Clercq** [comment]
2, change is easy. But better add a test as well which sends multiple accept headers (that test should fail before this change)
