### ISSUE TITLE
Protected operations

### ISSUE THREAD

**Issue by cahytinne** [OnroerendErfgoed/pyramid_urireferencer#5]
Include decorator which can be used in an applications to block operations (for example delete) on a certain uri that might be used in external applications.

**Comment by cahytinne** [comment]
* https://github.com/OnroerendErfgoed/pyramid_urireferencer/blob/master/pyramid_urireferencer/protected_resources.py
* https://github.com/OnroerendErfgoed/pyramid_urireferencer/blob/master/tests/test_protected_resources.py

**Comment by koenedaele** [comment]
Currently the decorator raises an HTTP 500 error when the response came back as success False. This means that one of the subrequests failed. In this case, even though some of the requests failed, we still might have received information that the URI is in use in some other application. Which is sufficient to warrant the conflict exception in stead of the 500.

So: if response = False. Check if some of the subrequests succeeded and if those have references. Is some references were found, raise HTTPConflict. If response = False, and no subrequests succeeded or the ones that succeeded did not find a reference, raise an internal server error.

**Comment by cahytinne** [comment]
https://github.com/OnroerendErfgoed/pyramid_urireferencer/commit/3b76cdf27f9eb80a5de7fbe94eb67d2a47b94e5b
