### ISSUE TITLE
Nieuwe protected decorator toevoegen die de request niet uit de parent haalt maar rechtstreeks

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/pyramid_urireferencer#50]
https://github.com/OnroerendErfgoed/pyramid_urireferencer/blob/248978aa26b9032e8cccb5db7edfb78a2112fc38/pyramid_urireferencer/protected_resources.py#L19

De huidige implementatie gaat ervan uit dat er steeds een attribuut request is op de eerste parameter. Dit is voor veel van onze nieuwe projecten niet meer het geval, daar is de request zelf gewoon de eerste parameter. Nu lossen we dit op als volgt:

https://github.com/OnroerendErfgoed/beeldbank/blob/cc0d802c3d7fc4463fd915d985c9afd667b4ab88/beeldbankbeheer/beeldbankbeheer/views/__init__.py#L17

Los van het feit dat dit redelijk onleesbaar wordt, zit diezelfde code nu ook al in verschillende projecten. Dus naast de bestaande decorator een 2de voorzien die exact hetzelfde doet maar dan met ``` def advice(request, *args, **kw): ``` ipv ``` def advice(parent_object, *args, **kw): ``` en gewoon ``` request ``` ipv ``` parent_object.request ```.

**Comment by koenedaele** [comment]
Moet die oudere versie dan deprecated worden of blijft die zinnig?

Gelieve de docs van pyramid_urireferencer meteen ook goed up te daten. Begint soms redelijk onbegrijpbaar te worden. Kan dit alles toch niet cleaner en minder hard gekoppeld geïmplementeerd worden?

**Comment by claeyswo** [comment]
> Moet die oudere versie dan deprecated worden of blijft die zinnig?

Deprecated idd

**Comment by Wim-De-Clercq** [comment]
Zou je niet ipv een decorator iets zoals deze custom view derives kunnen gebruiken?
https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#custom-view-derivers

We moeten dan gewoon aan de `RouteConfigArgs` in `oe_utils` een parameter `protected` ofzo toevoegen. En bij het definieren van de services deze dan op True zetten waar nodig.
Die view-deriver wordt uitgevoerd na de security `__acl__` checks en voor de view zelf. 
In die deriver is de `request` vanuit pyramid beschikbaar dus moet je niet afhangen van de parameters in de function die gedecoreert is om eraan te geraken.

Die view-deriver kan geregistreerd worden bij de `config.include('pyramid_urireferencer')` includeme code.

Je kan dan natuurlijk enkel heel de view protected zetten en geen kleinere function. Maar in de meeste code die ik zie is dit voldoende.

**Comment by claeyswo** [comment]
Ik heb het niet volledig gelezen dus ben maar half mee. Maar als dat op het niveau van de RouteConfigArgs zou geregeld kunnen worden lijkt mij dat een goed idee.

**Comment by koenedaele** [comment]
Lijkt pas te kunnen vanaf pyramid 1.7, dus in dat geval wel graag de min. requirement van de lib op 1.7 te zetten. Zou voor de rest wel cleaner zijn, dus ok voor mij.

**Comment by Wim-De-Clercq** [comment]
Om de view deriver te gebruiken is ook nog een change in `oe_utils.views.__init__` nodig.
`protected` toevoegen aan de `RouteConfigArgs`.
