### ISSUE TITLE
twine check

### ISSUE THREAD

**Issue by axd1967** [OnroerendErfgoed/pyramid_urireferencer#64]
Zie https://github.com/OnroerendErfgoed/scripts/issues/299

**Comment by JonasGe** [comment]
Het probleem is hier dat Pypi geen Sphinx markdown gebruikt dus die speciale termen worden niet aanvaard.

Voor deze applicatie gaat het om 2 termen in de changelog: `:class:` en `:meth:`

Simpele fix is die termen uit de changelog halen. Ze kunnen toch niet deftig getoond worden op Pypi.
