### ISSUE TITLE
protected resource decorator makes a lot of assumptions

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/pyramid_urireferencer#7]
This decorators assumes it's decorating a class-based view. As it currently is I don't think it could decorate a functional view (because in that case the request is a function parameter, not an attribute).

Also, it assumes the matchdict of the request contains a value `id`. And that the class it's decorating has an attribute `uri_template`.

Are there cleaner ways of dealing with this? At least the docs should reflect this. Now you can only decorate a very specific type of function and this will fail when the function isn't what we expect it to be.

@BartSaelen Thoughts?

**Comment by koenedaele** [comment]
Noticed this when looking at OnroerendErfgoed/besluiten#159

**Comment by cahytinne** [comment]
I created the decorator bases on [the one in atramhasis](https://github.com/OnroerendErfgoed/atramhasis/blob/master/atramhasis/protected_resources.py#L19-L31).

Here the parent object is also assumed to be a class with a request attribute. The decorator also presumes that the path url is the `uri` of the resource. 

The `uri_template` is necessary to construct the `uri` (together with the `id`). I thought of the possibility of adding a constant in to the view which uses the decorator, so it can be passed as a variable to the decorator function. But the config settings (including the `uri_template`) are already included in the request. 

I have added documentation [here](https://github.com/OnroerendErfgoed/pyramid_urireferencer/blob/master/pyramid_urireferencer/protected_resources.py#L20-L23). This is for the next release.

I can add more lines to inform the developer of misusing the decorator: when the parent object is not a class, not containing a request, not containing a template_uri.

**Comment by koenedaele** [comment]
Ok. Interesting. The Atramhasis one is a bit less problematic because it's inherently assumed to only be used within Atramhasis. Although we should probably also document there that it only works with class based views that have a request attribute. I'm wondering how this works in normal pyramid since the view_config decorator seem to work for both types of views? I think they're using something called Venusian?

I don't mind getting stuff out of the request, that's kind of inevitable. Not completely sure if `uri_template` is a good variable name. Do we risk running into name clashes there?

**Comment by koenedaele** [comment]
Possibly #8 is so related these two tickets can't be handled separately.
