### ISSUE TITLE
Protected resource URI generation should be more flexible.

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/pyramid_urireferencer#8]
Currently the protected resource decorator assumes that the URI of the resource it's protecting can be generated based on a simple template and the resource object's id. While this works most of the time, there will be cases where that's too simplistic (See OnroerendErfgoed/adviezen#210).

Eg. when a certain resource has different URI's based on a subtype of a resource. Eg, when we have a resource shapes that has two subtypes: circles and squares. The URI's in use might be `shapes/<id>`, but they might also be `circles/<id>` and `squares/<id>` based on the subtype.

This might also happen because we have a uri like `https://id.erfgoed.net/actoren/501/adressen/15`. In this case a template with just an id is insufficient.

Maybe we can implement this with a callback function that is passed the resource it's protecting? But maybe we currently don't have the resource until after we've executed the view?

/cc @BartSaelen

**Comment by cahytinne** [comment]
Is following suggestion OK?

The `parent_object` (View) should own a function that returns a URI. The name of the function should be `get_uri`. Example `get_uri` function:


```python
class View(object):
    def __init__(self, request):
       self.request = request
    
    def get_uri():
        _uri = self.request.registry.settings['resource.uri']
   	id = self.request.matchdict['id']
        return _uri.format(id)
```

The protected_operation function could retrieve the URI as followed:


```python
def protected_operation(fn):
    def advice(parent_object, *args, **kw):
          uri = parent_object.get_uri()
```

In this case, the only assumption is the name of the `get_uri` function. 


Is it necessary to refactor the decorator so the name of the function is passed as a parameter?

**Comment by koenedaele** [comment]
So, in this case if we have both `circle` and `square` resources, they should have different View classes with different functions?

It's a good fix for this issue, but it does not help with #7, but maybe we can tackle that one later.

Also, can we change the function name to something like urireferencer_get_uri()? To reduce the possibilities of name clashes.

**Comment by cahytinne** [comment]
It's also possible to have both `circle` and `square` resources in the same View classes with one function. For example:

```python
class View(object):
    def __init__(self, request):
       self.request = request

    def urireferencer_get_uri(self):
        id = self.request.matchdict['id']
        if self.data_manager.get(id).shape == 'circle':
            return self.request.registry.settings['circle.uri'].format(id)
        elif self.data_manager.get(id).shape == 'square':
            return self.request.registry.settings['square.uri'].format(id)
        else:
            return self.request.registry.settings['default.uri'].format(id)
```

The way in which the URI is returned is now fully in the hands of the `parent_object` (the View). The only assumption is the name of that function. I will rename it. `urireferencer_get_uri` is better.

**Comment by koenedaele** [comment]
We might also have 2 resources with different id sequences (and different datamanagers), but I assume we'll be able to work around that.

**Comment by BartSaelen** [comment]
The solution has a way to high coupling between the 2 objects, but this was also the case with the original solution. Not really happy with it, but I don't have a better solution at the moment.

**Comment by BartSaelen** [comment]
At least we should enforce the method on to the parent using an interface.

**Comment by BartSaelen** [comment]
And add a check to see if the function actually exists
