### ISSUE TITLE
Error message when a backend application can't be reached

### ISSUE THREAD

**Issue by cahytinne** [OnroerendErfgoed/pyramid_urireferencer#9]
When a service is not reachable for the uriregistry.

AS IS:
HTTPInternalServerError: Urireferencer: Something went wrong while retrieving references of the uri https://id.erfgoed.net/besluiten/1

TO BE:
HTTP 503 Service Unavailable: Urireferencer: Something went wrong while retrieving references of the uri https://id.erfgoed.net/test/1. Application A not reachable.

**Comment by koenedaele** [comment]
No longer certain what we should be returning here. A 503 would indicate something temporary. A 502 Bad Gateway would be an option as well. In the end, let's just keep things at a 500 Internal Server Error, but expand the error message, like in #10 

Current message:
*Urireferencer: Something went wrong while retrieving references of the uri https://id.erfgoed.net/actoren/1*

Let's change this to:
*Unable to verify the uri https://id.erfgoed.net/actoren/1 is no longer being used. Could not verify with https://besluiten.onroerenderfgoed.be*

I would also want to see the following JSON error message:

```json
{
 "message": "Unable to verify the uri https://id.erfgoed.net/actoren/1 is no longer being used.",
 "errors": [
  "https://besluiten.onroerenderfgoed.be: Could not verify uri is no longer being used."
 ],
 "registry_response": <Include the response the registry passed so the client can create custom error messages>
}
```
